### ISSUE TITLE
Bug when spot sources are long strings.

### ISSUE THREAD

**Issue by cwhelchel** [cwhelchel/hunterlog#1]
For spot comments, the source property can be longer than the configured DB column. 

```
VM9:451  Uncaught (in promise) Traceback (most recent call last):
  File ".venv\lib\site-packages\webview\util.py", line 194, in _call
    result = func(*func_params.values())
  File "src\api.py", line 65, in insert_spot_comments
    self.db.insert_spot_comments(spot.activator, spot.reference, comms)
  File "src\db\db.py", line 235, in insert_spot_comments
    to_add = ss.load(comments, session=self.session)
  File ".venv\lib\site-packages\marshmallow_sqlalchemy\load_instance_mixin.py", line 100, in load
    return super().load(data, **kwargs)
  File ".venv\lib\site-packages\marshmallow\schema.py", line 723, in load
    return self._do_load(
  File ".venv\lib\site-packages\marshmallow\schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {59: {'source': ['Longer than maximum length 10.']}}
```

this was caused by this spot comment, thanks Matt 😆:

```
K1MBK
CW on 20m (14056 kHz) at 00:08 UTC via Ham2K Portable Logger
CW [Ham2K PoLo]
```

**Comment by cwhelchel** [comment]
Fixed in v0.0.1l
